### ISSUE TITLE
Cannot find module 'web3-requestManager'

### ISSUE THREAD

**Issue by muhammadsr** [martriay/token-vesting-ui#1]
Any idea why I am getting the following error?

```
MUHAMMADs-MacBook-Pro-2:token-vesting-ui muhammad$ npx truffle compile
Error: Cannot find module 'web3-requestManager'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/muhammad/Desktop/RentHoop/Solidity/dev/token-vesting-ui/node_modules/web3/packages/web3-core/src/index.js:26:22)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/muhammad/Desktop/RentHoop/Solidity/dev/token-vesting-ui/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
MUHAMMADs-MacBook-Pro-2:token-vesting-ui muhammad$ 
```

**Comment by muhammadsr** [comment]
Nvm....Running `npm install ethereum/web3.js` fixed my issue. I had an unstable version of web3.
